supportLabel: support

supportComment: >
  :wave: @{issue-author}, we use the issue tracker exclusively for bug reports
  and feature requests. However, this issue appears to be a support request.
  Please join our [discord](https://lemmotresto.com/discord) and go to the #support channel and place your support request there.

close: true

lock: false