# Mob-list
# This list is the chances and the amount of coins the mobs drop when killed.
#
# Chance: the chance for the amount to be dropped. Make this 100 if you want it to always drop the amount.
# Amount: the amount to be dropped. This can be randomized by doing:
# amount: "minimumvalue-maximumvalue"
# For example I want to drop a random amount ranging from 2 to 8 coins
# Then I would do:
# amount: "2-8"
mob-list:
  blaze:
    chance: 5
    amount: "1-2"
  skeleton:
    chance: 5
    amount: 1
  zombie:
    chance: 5
    amount: 1
  creeper:
    chance: 8
    amount: 1
  enderman:
    chance: 8
    amount: 1
  wither:
    chance: 50
    amount: 1

# This is the gui!
# The command is what is used to open the shop!
# Rows is the amount of rows you want in the gui make sure you set your items accordingly otherwise it will error.
# The items list allows you to add as many items as you want!
# The name // identifier can be anything and will just be used as the permission for this item.
# Glowing is if the item looks like it is enchanted.
# Permission is a boolean (true/false) if you want everyone to be able to buy this and not require a permission set this to false otherwise set it to true!
# The price in mobcoins that you need to make this purchase.
# The commands to run after purchase.
gui:
  name: "Mob Coin Shop!"
  command: "/coinshop"
  rows: 1
  items:
    diasword:
      slot: 1
      material: DIAMOND_SWORD
      amount: 1
      displayname: "&6&lDagger Sword"
      glowing: true
      lore:
      - " &6* &eINFO: &fThe best sword"
      - "   &fon the server. You can't"
      - "   &fpass up this deal!"
      - ""
      - " &6* &ePRICE: &7100 coins"
      - ""
      - "&7&o(( Click to &f&opurchase &7&othis &f&o'&6&l&oDagger Sword&f&o'&7&o! ))"
      permission: false
      price: 100
      commands:
      - "eco give %player% diamond_sword"